# SPDX-FileCopyrightText: 2025 Helmholtz-Zentrum hereon GmbH
# SPDX-FileContributor: Carsten Lemmen <carsten.lemmen@hereon.de>
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "TAME"
SPDX-PackageSupplier = "Carsten Lemmen <carsten.lemmen@hereon.de>"

[[annotations]]
path = ["setup/0d/env**dat", "testcases/phytoplankton/env**dat"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Helmholtz-Zentrum hereon GmbH"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["setup/1d-cuxhaven/data/meteofile.csv"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Helmholtz-Zentrum hereon GmbH"
SPDX-License-Identifier = "CC0-1.0"
