# SPDX-FileCopyrightText: 2025 Helmholtz-Zentrum hereon GmbH
# SPDX-License-Identifier: CC0-1.0

name: Security Analysis

on:
  push:
    branches: [main, ci] # Adjust if other branches are primary development/release branches
  pull_request:
    branches: [main, ci] # Adjust if other branches are primary development/release branches
  schedule:
    - cron: '30 2 * * 1' # Example: Run every Monday at 2:30 AM UTC

jobs:
  codeql_analysis: # Renamed job ID for clarity
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python
      - name: Autobuild
        uses: github/codeql-action/autobuild@v4
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
