# SPDX-FileCopyrightText: 2025 Helmholtz-Zentrum hereon GmbH
# SPDX-License-Identifier: CC0-1.0

name: Build and Test

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]

jobs:
  build-python-package:
    name: Build Python Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install python tools
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - name: Install build tools
        run: python -m pip install -U pip build twine
      - name: Build package
        run: make dist
      - name: Check dist
        run: twine check dist/*
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts # Used by deployment job
          path: dist/*

  test-python-units:
    name: Python Unit Tests
    runs-on: ubuntu-latest
    container: python:3.12 # From original test job
    strategy:
      matrix:
        scenario: [default] # From original test job
    env:
      PIPENV_PIPFILE: ci/matrix/${{ matrix.scenario }}/Pipfile # From original test job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install python tools
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies (pipenv)
        run: pipenv install --dev # Install dev to ensure pytest and cov are there
      - name: Run Pytest
        run: pipenv run pytest -v --cov=python -x
      - name: Upload pipfile artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipfile-${{ matrix.scenario }} # Make artifact name unique per scenario
          path: ${{ env.PIPENV_PIPFILE }} # Upload the Pipfile itself
